---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "marketplace-gateway.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ template "marketplace-gateway.fullname" . }}
    app.kubernetes.io/component: marketplace-gateway
    app.kubernetes.io/part-of: applications
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.servicePort }}
  selector:
    app.kubernetes.io/name: {{ template "marketplace-gateway.fullname" . }}
