---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "marketplace-gateway.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ template "marketplace-gateway.fullname" . }}
    app.kubernetes.io/component: marketplace-gateway
    app.kubernetes.io/part-of: applications
spec:
  endpoints:
  - port: http
    basicAuth:
      password:
        name: admin
        key: password
      username:
        name: admin
        key: user
    path: /actuator/prometheus
    interval: 30s
    relabelings:
    - action: replace
      sourceLabels: [__meta_kubernetes_pod_name]
      targetLabel: instance
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "marketplace-gateway.fullname" . }}
  namespaceSelector:
    matchNames:
    matchNames:
    - {{ .Values.namespace }}
