---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - project.yaml
  - marketplace-gateway.yaml

generatorOptions:
  # mess around with this later, after testing, flux/helm already kinda hash, so likely we'll want kustomize to do so too
  disableNameSuffixHash: true
